[versions]
agp = "8.6.1"
kotlin = "2.0.20"
core-ktx = "1.15.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
appcompat = "1.7.0"
leakcanary = "2.14"
material = "1.12.0"
constraintlayout = "2.2.0"
navigation-fragment-ktx = "2.8.3"
google-appset = "16.1.0"
google-ads-identifier = "18.1.0"
tapsell = "1.0.2-beta02"
lifecycle-livedata-ktx = "2.8.7"
lifecycle-viewmodel-ktx = "2.8.7"
lifecycle-runtime-ktx = "2.8.7"
activity = "1.9.3"
activity-compose = "1.9.3"
compose-bom = "2024.10.01"
coil = "2.6.0"
appium = "9.3.0"

[libraries]
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-fragment-ktx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-fragment-ktx" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
google-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "google-ads-identifier" }
google-appset = { module = "com.google.android.gms:play-services-appset", version.ref = "google-appset" }
tapsell = { module = "ir.tapsell.mediation:tapsell", version.ref = "tapsell" }
adapter-legacy = { module = "ir.tapsell.mediation.adapter:legacy", version.ref = "tapsell" }
adapter-legacy-ima-extension = { module = "ir.tapsell.mediation.adapter:legacy-ima-extension", version.ref = "tapsell" }
adapter-admob = { module = "ir.tapsell.mediation.adapter:admob", version.ref = "tapsell" }
adapter-unityads = { module = "ir.tapsell.mediation.adapter:unityads", version.ref = "tapsell" }
adapter-mintegral = { module = "ir.tapsell.mediation.adapter:mintegral", version.ref = "tapsell" }
adapter-fyber = { module = "ir.tapsell.mediation.adapter:fyber", version.ref = "tapsell" }
adapter-applovin = { module = "ir.tapsell.mediation.adapter:applovin", version.ref = "tapsell" }
adapter-ironsource = { module = "ir.tapsell.mediation.adapter:ironsource", version.ref = "tapsell" }
adapter-liftoff = { module = "ir.tapsell.mediation.adapter:liftoff", version.ref = "tapsell" }
adapter-yandex = { module = "ir.tapsell.mediation.adapter:yandex", version.ref = "tapsell" }
adapter-chartboost = { module = "ir.tapsell.mediation.adapter:chartboost", version.ref = "tapsell" }
adapter-wortise = { module = "ir.tapsell.mediation.adapter:wortise", version.ref = "tapsell" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }

appium = { module = "io.appium:java-client", version.ref = "appium" }

androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]

